apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-angular-app
  template:
    metadata:
      labels:
        app: my-angular-app
    spec:
      containers:
        - name: my-angular-app
          image: my-angular-app:latest
          ports:
            - containerPort: 80
