name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Build Docker image
        run: |
          docker build -t my-angular-app .
          docker tag my-angular-app:latest <your-dockerhub-username>/my-angular-app:latest

      - name: Push Docker image to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker push <your-dockerhub-username>/my-angular-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install kubectl
        run: sudo apt-get install -y kubectl

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
